# Generated by Django 6.0.4 on 2026-04-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='text',
            new_name='steps',
        ),
    ]
