# Generated by Django 6.0.4 on 2026-04-13 14:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_text_step_steps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='steps',
            new_name='description',
        ),
        migrations.AddField(
            model_name='step',
            name='duration',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='responsible',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
